### ISSUE TITLE
igc-combo api reference links are broken

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-xplat-docs#788]
I'm trying to get to the API docs of the `igc-combo` component. Some of the items have no links and the `IgcComboComponent` link returns a 404:

https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/overview#api-reference

**Comment by HUSSAR-mtrela** [comment]
@mddifilippo89 check if list items with missing API links are present in API mapping files or if they have diffrent orginal names: 
https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/combo/overview#api-reference

![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/11665978/691ba358-9abb-4904-9025-24fe0e65e6bb)

**Comment by mddifilippo89** [comment]
Not sure we even need to mention these since none of the docs or samples use these other typpes. I also see "blazorSuppress" so perhaps this is the reason they're not in the API

https://github.com/IgniteUI/igniteui-webcomponents/blob/master/src/components/combo/combo-item.ts
https://github.com/IgniteUI/igniteui-webcomponents/blob/master/src/components/combo/combo-header.ts
https://github.com/IgniteUI/igniteui-webcomponents/blob/master/src/components/combo/combo-list.ts

@HUSSAR-mtrela 
https://github.com/IgniteUI/igniteui-xplat-docs/compare/mdd-remove-unnecessary-combo-types?expand=1
