### ISSUE TITLE
Rating topic is returning 404

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-xplat-docs#833]
Open the rating docs on prod for Blazor or WC:
https://www.infragistics.com/products/ignite-ui-blazor/blazor/components/inputs/rating

Result:
![image](https://github.com/IgniteUI/igniteui-xplat-docs/assets/11193764/2cce7dd2-110c-4abe-858e-3cb4c42cadb8)

**Comment by radomirchev** [comment]
@HUSSAR-mtrela the issue is critical, we have marketing materials pointing to that topic and they return error 404!

**Comment by HUSSAR-mtrela** [comment]
@zdrawku @radomirchev 

the Rating topic is excluded from Blazor docs:
https://github.com/IgniteUI/igniteui-xplat-docs/blob/vnext/docfx/en/components/toc.json#L1696
because it does not contain Blazor code snippets AND we do not have Blazor samples for it:
https://github.com/IgniteUI/igniteui-blazor-examples/tree/vnext/samples/inputs

**Comment by radomirchev** [comment]
@simeonoff
